// Ligas soportadas para búsqueda de equipos/favoritos (vía ESPN /teams, no depende de partidos jugados).
export const LIGAS = [
  { label: 'Alemania — Bundesliga',       code: 'ger.1' },
  { label: 'Alemania — 2. Bundesliga',    code: 'ger.2' },
  { label: 'Argentina — Liga Profesional',code: 'arg.1' },
  { label: 'Australia — A-League',        code: 'aus.1' },
  { label: 'Bélgica — First Division A',  code: 'bel.1' },
  { label: 'Bolivia — Liga Profesional',  code: 'bol.1' },
  { label: 'Brasil — Série A',            code: 'bra.1' },
  { label: 'Dinamarca — Superliga',       code: 'den.1' },
  { label: 'Escocia — Premiership',       code: 'sco.1' },
  { label: 'España — La Liga',            code: 'esp.1' },
  { label: 'España — Segunda División',   code: 'esp.2' },
  { label: 'Francia — Ligue 1',           code: 'fra.1' },
  { label: 'Inglaterra — Premier League', code: 'eng.1' },
  { label: 'Inglaterra — Championship',   code: 'eng.2' },
  { label: 'Italia — Serie A',            code: 'ita.1' },
  { label: 'Italia — Serie B',            code: 'ita.2' },
  { label: 'México — Liga MX',            code: 'mex.1' },
  { label: 'MLS',                         code: 'usa.1' },
  { label: 'Noruega — Eliteserien',       code: 'nor.1' },
  { label: 'Países Bajos — Eredivisie',   code: 'ned.1' },
  { label: 'Portugal — Primeira Liga',    code: 'por.1' },
  { label: 'Suecia — Allsvenskan',        code: 'swe.1' },
  { label: 'Turquía — Süper Lig',         code: 'tur.1' },
]
