<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520061426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE acciones_analisis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, raw_income JSON NOT NULL, raw_balance JSON NOT NULL, raw_cashflow JSON NOT NULL, metrics JSON NOT NULL, score VARCHAR(20) NOT NULL, score_detail JSON NOT NULL, investment_type VARCHAR(30) DEFAULT NULL, stage VARCHAR(50) DEFAULT NULL, speculative_type VARCHAR(20) DEFAULT NULL, portrait TEXT NOT NULL, price_at_analysis NUMERIC(15, 4) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_10137E8BD17F50A6 ON acciones_analisis (uuid)');
        $this->addSql('CREATE INDEX idx_analisis_accion ON acciones_analisis (accion_id)');
        $this->addSql('ALTER TABLE acciones_analisis ADD CONSTRAINT FK_10137E8B3F4B5275 FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_favoritos_uuid RENAME TO UNIQ_9E442EC8D17F50A6');
        $this->addSql('DROP INDEX idx_ligas_gpm_gpm');
        $this->addSql('DROP INDEX idx_ligas_gpm_pais');
        $this->addSql('ALTER TABLE futbol_ligas_gpm ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE futbol_ligas_gpm ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE futbol_ligas_gpm ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX futbol_ligas_gpm_uuid_key RENAME TO UNIQ_E239E9F0D17F50A6');
        $this->addSql('ALTER INDEX futbol_ligas_gpm_codigo_espn_key RENAME TO UNIQ_E239E9F09EFC067F');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acciones_analisis DROP CONSTRAINT FK_10137E8B3F4B5275');
        $this->addSql('DROP TABLE acciones_analisis');
        $this->addSql('ALTER INDEX uniq_9e442ec8d17f50a6 RENAME TO uniq_favoritos_uuid');
        $this->addSql('ALTER TABLE futbol_ligas_gpm ALTER id SET DEFAULT nextval(\'futbol_ligas_gpm_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE futbol_ligas_gpm ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE futbol_ligas_gpm ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_ligas_gpm_gpm ON futbol_ligas_gpm (gpm)');
        $this->addSql('CREATE INDEX idx_ligas_gpm_pais ON futbol_ligas_gpm (pais)');
        $this->addSql('ALTER INDEX uniq_e239e9f0d17f50a6 RENAME TO futbol_ligas_gpm_uuid_key');
        $this->addSql('ALTER INDEX uniq_e239e9f09efc067f RENAME TO futbol_ligas_gpm_codigo_espn_key');
    }
}
