<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260425034720 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Redesign portafolio: portafolios (container) + portafolio_acciones (junction)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE portafolio DROP CONSTRAINT IF EXISTS fk_fe2be66a3f4b5275');
        $this->addSql('DROP TABLE IF EXISTS portafolio');

        $this->addSql('CREATE TABLE portafolios (
            id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid        VARCHAR(36) NOT NULL,
            nombre      VARCHAR(100) NOT NULL,
            descripcion TEXT DEFAULT NULL,
            created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_portafolios_uuid ON portafolios (uuid)');

        $this->addSql('CREATE TABLE portafolio_acciones (
            id                INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid              VARCHAR(36) NOT NULL,
            portafolio_id     INT NOT NULL,
            accion_id         INT NOT NULL,
            status            VARCHAR(20) DEFAULT \'watchlist\' NOT NULL,
            precio_referencia NUMERIC(15, 4) DEFAULT NULL,
            notas             TEXT DEFAULT NULL,
            created_at        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_portafolio_acciones_uuid ON portafolio_acciones (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uq_portafolio_accion ON portafolio_acciones (portafolio_id, accion_id)');
        $this->addSql('CREATE INDEX idx_portafolio_acciones_status ON portafolio_acciones (status)');
        $this->addSql('ALTER TABLE portafolio_acciones ADD CONSTRAINT fk_pa_portafolio FOREIGN KEY (portafolio_id) REFERENCES portafolios (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portafolio_acciones ADD CONSTRAINT fk_pa_accion FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE portafolio_acciones DROP CONSTRAINT fk_pa_portafolio');
        $this->addSql('ALTER TABLE portafolio_acciones DROP CONSTRAINT fk_pa_accion');
        $this->addSql('DROP TABLE portafolio_acciones');
        $this->addSql('DROP TABLE portafolios');

        $this->addSql('CREATE TABLE portafolio (
            id                INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid              VARCHAR(36) NOT NULL,
            accion_id         INT NOT NULL,
            status            VARCHAR(20) DEFAULT \'watchlist\' NOT NULL,
            precio_referencia NUMERIC(15, 4) DEFAULT NULL,
            notas             TEXT DEFAULT NULL,
            created_at        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('ALTER TABLE portafolio ADD CONSTRAINT fk_fe2be66a3f4b5275 FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE');
    }
}
