<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260810000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create acciones_earnings_reports table for raw earnings documents';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<SQL
            CREATE TABLE acciones_earnings_reports (
                id                    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                accion_id             INT NOT NULL,
                uuid                  VARCHAR(36) NOT NULL,
                source                VARCHAR(20) NOT NULL,
                form_type             VARCHAR(20) NOT NULL,
                accession_number      VARCHAR(20) DEFAULT NULL,
                cik                   VARCHAR(20) DEFAULT NULL,
                filing_date           DATE DEFAULT NULL,
                report_date           DATE DEFAULT NULL,
                primary_document_name VARCHAR(255) DEFAULT NULL,
                exhibit_document_name VARCHAR(255) DEFAULT NULL,
                filing_url            VARCHAR(1000) DEFAULT NULL,
                index_url             VARCHAR(1000) DEFAULT NULL,
                exhibit_url           VARCHAR(1000) DEFAULT NULL,
                periodic_report_url   VARCHAR(1000) DEFAULT NULL,
                items                 TEXT DEFAULT NULL,
                content_format        VARCHAR(20) NOT NULL,
                raw_content           TEXT NOT NULL,
                metadata              JSON NOT NULL,
                fetched_at            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_earnings_report_uuid ON acciones_earnings_reports (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_earnings_report_accion_accession ON acciones_earnings_reports (accion_id, accession_number)');
        $this->addSql('CREATE INDEX idx_earnings_report_accion_filing ON acciones_earnings_reports (accion_id, filing_date)');
        $this->addSql('CREATE INDEX idx_earnings_report_source_form ON acciones_earnings_reports (source, form_type)');
        $this->addSql('ALTER TABLE acciones_earnings_reports ADD CONSTRAINT FK_earnings_report_accion FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE acciones_earnings_reports DROP CONSTRAINT FK_earnings_report_accion');
        $this->addSql('DROP TABLE acciones_earnings_reports');
    }
}
