<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260516000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create acciones_earnings table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE acciones_earnings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, earnings_date DATE NOT NULL, eps_estimate NUMERIC(10, 4) DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_earnings_accion ON acciones_earnings (accion_id)');
        $this->addSql('ALTER TABLE acciones_earnings ADD CONSTRAINT FK_earnings_accion FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE acciones_earnings DROP CONSTRAINT FK_earnings_accion');
        $this->addSql('DROP TABLE acciones_earnings');
    }
}
