<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426191807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE futbol_analisis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, texto_libre TEXT DEFAULT NULL, pred_ganador VARCHAR(20) DEFAULT NULL, pred_goles_local INT DEFAULT NULL, pred_goles_visitante INT DEFAULT NULL, pred_over_under NUMERIC(4, 1) DEFAULT NULL, pred_corners INT DEFAULT NULL, pred_jugador_destacado VARCHAR(100) DEFAULT NULL, acierto_ganador BOOLEAN DEFAULT NULL, acierto_goles BOOLEAN DEFAULT NULL, acierto_corners BOOLEAN DEFAULT NULL, acierto_jugador BOOLEAN DEFAULT NULL, notas_resultado TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, partido_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F7EBEC3AD17F50A6 ON futbol_analisis (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F7EBEC3A11856EB4 ON futbol_analisis (partido_id)');
        $this->addSql('CREATE TABLE futbol_ligas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, nombre VARCHAR(100) NOT NULL, codigo_espn VARCHAR(20) NOT NULL, pais VARCHAR(50) NOT NULL, division INT DEFAULT 1 NOT NULL, activa BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E463D652D17F50A6 ON futbol_ligas (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E463D6529EFC067F ON futbol_ligas (codigo_espn)');
        $this->addSql('CREATE INDEX idx_liga_codigo ON futbol_ligas (codigo_espn)');
        $this->addSql('CREATE INDEX idx_liga_activa ON futbol_ligas (activa)');
        $this->addSql('CREATE TABLE futbol_partidos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, espn_event_id VARCHAR(30) NOT NULL, fecha DATE NOT NULL, hora_utc TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, equipo_local VARCHAR(100) NOT NULL, equipo_visitante VARCHAR(100) NOT NULL, estadio VARCHAR(150) DEFAULT NULL, estado VARCHAR(20) DEFAULT \'programado\' NOT NULL, pos_local INT DEFAULT NULL, pos_visitante INT DEFAULT NULL, pts_local INT DEFAULT NULL, pts_visitante INT DEFAULT NULL, pj_local INT DEFAULT NULL, pj_visitante INT DEFAULT NULL, forma_local VARCHAR(20) DEFAULT NULL, forma_visitante VARCHAR(20) DEFAULT NULL, odds_local NUMERIC(6, 2) DEFAULT NULL, odds_empate NUMERIC(6, 2) DEFAULT NULL, odds_visitante NUMERIC(6, 2) DEFAULT NULL, spread NUMERIC(5, 2) DEFAULT NULL, over_under NUMERIC(5, 2) DEFAULT NULL, prob_local NUMERIC(5, 2) DEFAULT NULL, prob_empate NUMERIC(5, 2) DEFAULT NULL, prob_visitante NUMERIC(5, 2) DEFAULT NULL, h2h_ganados_local INT DEFAULT NULL, h2h_ganados_visitante INT DEFAULT NULL, h2h_empates INT DEFAULT NULL, h2h_detalle JSON DEFAULT NULL, score_analisis INT DEFAULT 0 NOT NULL, score_detalle JSON DEFAULT NULL, goles_local INT DEFAULT NULL, goles_visitante INT DEFAULT NULL, goleadores JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, liga_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2B531363D17F50A6 ON futbol_partidos (uuid)');
        $this->addSql('CREATE INDEX IDX_2B531363CF098064 ON futbol_partidos (liga_id)');
        $this->addSql('CREATE INDEX idx_partido_fecha ON futbol_partidos (fecha)');
        $this->addSql('CREATE INDEX idx_partido_estado ON futbol_partidos (estado)');
        $this->addSql('CREATE UNIQUE INDEX uq_espn_event ON futbol_partidos (espn_event_id)');
        $this->addSql('CREATE TABLE futbol_seleccion_diaria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, fecha DATE NOT NULL, posicion INT DEFAULT 1 NOT NULL, razones JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, partido_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF4FBF13D17F50A6 ON futbol_seleccion_diaria (uuid)');
        $this->addSql('CREATE INDEX IDX_FF4FBF1311856EB4 ON futbol_seleccion_diaria (partido_id)');
        $this->addSql('CREATE INDEX idx_seleccion_fecha ON futbol_seleccion_diaria (fecha)');
        $this->addSql('CREATE UNIQUE INDEX uq_seleccion_partido ON futbol_seleccion_diaria (fecha, partido_id)');
        $this->addSql('ALTER TABLE futbol_analisis ADD CONSTRAINT FK_F7EBEC3A11856EB4 FOREIGN KEY (partido_id) REFERENCES futbol_partidos (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE futbol_partidos ADD CONSTRAINT FK_2B531363CF098064 FOREIGN KEY (liga_id) REFERENCES futbol_ligas (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE futbol_seleccion_diaria ADD CONSTRAINT FK_FF4FBF1311856EB4 FOREIGN KEY (partido_id) REFERENCES futbol_partidos (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE futbol_analisis DROP CONSTRAINT FK_F7EBEC3A11856EB4');
        $this->addSql('ALTER TABLE futbol_partidos DROP CONSTRAINT FK_2B531363CF098064');
        $this->addSql('ALTER TABLE futbol_seleccion_diaria DROP CONSTRAINT FK_FF4FBF1311856EB4');
        $this->addSql('DROP TABLE futbol_analisis');
        $this->addSql('DROP TABLE futbol_ligas');
        $this->addSql('DROP TABLE futbol_partidos');
        $this->addSql('DROP TABLE futbol_seleccion_diaria');
    }
}
