<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425024936 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE acciones_noticias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, date DATE NOT NULL, change_pct NUMERIC(8, 4) NOT NULL, title VARCHAR(500) NOT NULL, summary TEXT DEFAULT NULL, url VARCHAR(500) DEFAULT NULL, pub_date DATE DEFAULT NULL, agent_analysis TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_426A3701D17F50A6 ON acciones_noticias (uuid)');
        $this->addSql('CREATE INDEX IDX_426A37013F4B5275 ON acciones_noticias (accion_id)');
        $this->addSql('CREATE INDEX idx_noticias_accion_date ON acciones_noticias (accion_id, date)');
        $this->addSql('ALTER TABLE acciones_noticias ADD CONSTRAINT FK_426A37013F4B5275 FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acciones_noticias DROP CONSTRAINT FK_426A37013F4B5275');
        $this->addSql('DROP TABLE acciones_noticias');
    }
}
