<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260517000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create futbol_favoritos table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE futbol_favoritos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, espn_team_id VARCHAR(20) NOT NULL, espn_liga_code VARCHAR(20) NOT NULL, team_name VARCHAR(100) NOT NULL, liga_nombre VARCHAR(100) NOT NULL, pais VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_favoritos_uuid ON futbol_favoritos (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_favoritos_team_liga ON futbol_favoritos (espn_team_id, espn_liga_code)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE futbol_favoritos');
    }
}
