<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425022405 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE acciones (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, symbol VARCHAR(20) NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(10) NOT NULL, source VARCHAR(10) DEFAULT \'manual\' NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, alert_threshold_pct NUMERIC(5, 2) DEFAULT \'5.00\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29F5FFE7D17F50A6 ON acciones (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29F5FFE7ECC836F9 ON acciones (symbol)');
        $this->addSql('CREATE INDEX idx_acciones_symbol ON acciones (symbol)');
        $this->addSql('CREATE INDEX idx_acciones_active ON acciones (is_active)');
        $this->addSql('CREATE TABLE acciones_precios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, date DATE NOT NULL, price_open NUMERIC(15, 4) DEFAULT NULL, price_close NUMERIC(15, 4) NOT NULL, price_high NUMERIC(15, 4) DEFAULT NULL, price_low NUMERIC(15, 4) DEFAULT NULL, volume BIGINT DEFAULT NULL, prev_close NUMERIC(15, 4) DEFAULT NULL, change_pct NUMERIC(8, 4) DEFAULT NULL, change_amount NUMERIC(15, 4) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C525E6E4D17F50A6 ON acciones_precios (uuid)');
        $this->addSql('CREATE INDEX IDX_C525E6E43F4B5275 ON acciones_precios (accion_id)');
        $this->addSql('CREATE INDEX idx_precios_date ON acciones_precios (date)');
        $this->addSql('CREATE INDEX idx_precios_change ON acciones_precios (change_pct)');
        $this->addSql('CREATE UNIQUE INDEX uq_accion_date ON acciones_precios (accion_id, date)');
        $this->addSql('CREATE TABLE portafolio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, status VARCHAR(20) DEFAULT \'watchlist\' NOT NULL, precio_referencia NUMERIC(15, 4) DEFAULT NULL, notas TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE2BE66AD17F50A6 ON portafolio (uuid)');
        $this->addSql('CREATE INDEX IDX_FE2BE66A3F4B5275 ON portafolio (accion_id)');
        $this->addSql('CREATE INDEX idx_portafolio_status ON portafolio (status)');
        $this->addSql('ALTER TABLE acciones_precios ADD CONSTRAINT FK_C525E6E43F4B5275 FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE portafolio ADD CONSTRAINT FK_FE2BE66A3F4B5275 FOREIGN KEY (accion_id) REFERENCES acciones (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE categories ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE categories ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE categories ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX categories_slug_key RENAME TO UNIQ_3AF34668989D9B62');
        $this->addSql('ALTER TABLE studies ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE studies ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE studies ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE studies ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX studies_uuid_key RENAME TO UNIQ_C3A91A3FD17F50A6');
        $this->addSql('ALTER INDEX idx_study_tags_tag RENAME TO IDX_10647C1FBAD26311');
        $this->addSql('ALTER TABLE tags ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tags ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tags ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX tags_slug_key RENAME TO UNIQ_6FBC9426989D9B62');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acciones_precios DROP CONSTRAINT FK_C525E6E43F4B5275');
        $this->addSql('ALTER TABLE portafolio DROP CONSTRAINT FK_FE2BE66A3F4B5275');
        $this->addSql('DROP TABLE acciones');
        $this->addSql('DROP TABLE acciones_precios');
        $this->addSql('DROP TABLE portafolio');
        $this->addSql('ALTER TABLE categories ALTER id SET DEFAULT nextval(\'categories_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE categories ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE categories ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER INDEX uniq_3af34668989d9b62 RENAME TO categories_slug_key');
        $this->addSql('ALTER TABLE studies ALTER id SET DEFAULT nextval(\'studies_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE studies ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE studies ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE studies ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER INDEX uniq_c3a91a3fd17f50a6 RENAME TO studies_uuid_key');
        $this->addSql('ALTER INDEX idx_10647c1fbad26311 RENAME TO idx_study_tags_tag');
        $this->addSql('ALTER TABLE tags ALTER id SET DEFAULT nextval(\'tags_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tags ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE tags ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER INDEX uniq_6fbc9426989d9b62 RENAME TO tags_slug_key');
    }
}
